#!/bin/sh
# Copyright dunnhumby Germany GmbH 2017.
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
set -xeu

# libebtree is present
dpkg -L libebtree6-dev

# Minimal dmd and dmd-transitional test with rdmd and the converted code
echo 'void main() {}' > /tmp/x.d

dmd -run /tmp/x.d
rdmd --compiler=dmd /tmp/x.d
dmd-transitional -fPIC -run /tmp/x.d
rdmd --compiler=dmd-transitional -fPIC /tmp/x.d
