#!/bin/sh
set -eu

api="${api:-https://api.bintray.com}"
subj="${subj:-jfrog}"
repo="${repo:-jfrog-cli-go}"
pkg="${pkg:-jfrog-cli-linux-amd64}"
ver="${1:-$VERSION_JFROG}"
file="${file:-jfrog}"
dst="${dst:-/usr/local/bin/$file}"

# Get sha256 sum of the file
json=$(set -x; curl -#LkX GET "$api/packages/$subj/$repo/$pkg/versions/$ver/files")
# From the received array, select the object with the specific "path"
# attribute, and from that object get the "sha256" attribute
sha256=$(echo "$json" | jq -r ".[] | select(.path == \"$ver/$pkg/$file\") |
		.sha256")

# Get the file
(set -x; curl -#LkX GET "$api/$subj/$repo/download_file?file_path=$ver/$pkg/$file" > "$dst")

# Check file's sha256 sum
sha256new="$(sha256sum "$dst" | cut -c1-64)"
set -x
test "$sha256new" = "$sha256"

# Make it executable
chmod a+x "$dst"
