#!/bin/sh
# Copyright dunnhumby Germany GmbH 2017.
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
set -xeu

# Get utility stuff
. ./util.sh

dist="$(lsb_release -cs)"

# Add extra dlang APT repositories from Sociomantic and dlang-community in Bintray
apt_add_bintray_repos sociomantic-tsunami/ebtree sociomantic-tsunami/dlang \
		dlang-community/apt

# Add extra DMD D-APT repo
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EBCF975E5BA24D5E
# Added manually until D-APT is fixed
#wget http://downloads.sourceforge.net/project/d-apt/files/d-apt.list \
#               -O /etc/apt/sources.list.d/d-apt.list
echo "deb http://downloads.sourceforge.net/project/d-apt/ d-apt main" \
	> /etc/apt/sources.list.d/d-apt.list

if test "$(echo "$VERSION_DMD" | cut -d. -f1)" -eq 2 -a \
	"$(echo "$VERSION_DMD" | cut -d. -f2)" -ge 077
then
	DMD_PKG="dmd-compiler=$VERSION_DMD dmd-tools=$VERSION_DMD \
		libphobos2-dev=$VERSION_DMD"
else
	DMD_PKG="dmd-bin=$VERSION_DMD libphobos2-dev=$VERSION_DMD"
fi

# Install dlang packages
apt update
apt_pin_install \
	libebtree6="$VERSION_EBTREE" \
		libebtree6-dbg="$VERSION_EBTREE" \
		libebtree6-dev="$VERSION_EBTREE" \
	dmd-transitional="$VERSION_DMD_TRANSITIONAL" \
	$DMD_PKG \
	hmod="$VERSION_HMOD"

# Remove common temporary files and packages
cleanup
