#!/bin/sh
# Copyright dunnhumby Germany GmbH 2017.
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
set -xeu

# Get utility stuff
. ./util.sh

# Update apt and install base packages
apt_update_and_install_base_packages

# Add extra dlang APT repositories from Sociomantic in Bintray
apt_add_bintray_repos sociomantic-tsunami/ebtree sociomantic-tsunami/libdrizzle-redux \
		sociomantic-tsunami/mxnet

# Update the whole system
apt update
apt -y full-upgrade

# Remove common temporary files and packages
cleanup

# Add Yelp's dumb-init
curl -sL "https://github.com/Yelp/dumb-init/releases/download/v${VERSION_DUMB_INIT}/dumb-init_${VERSION_DUMB_INIT}_amd64" \
        -o /usr/local/bin/dumb-init
echo "${DUMB_INIT_SHA256} /usr/local/bin/dumb-init" | sha256sum -c
chmod +x /usr/local/bin/dumb-init
